### PR TITLE
Add method to retrieve the content stats

### LINKED ISSUE #6: Add API to retrieve the content stats
Currently, you can only listen to the `#update`. It'd also be cool if you could just retrieve the same information on demand.

Use case – you want to access that information on form submit to validate those values.

### LINKED ISSUE #2568: Add API to retrieve the content stats
Currently, you can only listen to the `#update`. It'd also be cool if you could just retrieve the same information on demand.

Use case – you want to access that information on form submit to validate those values.

### PR DESCRIPTION
**Pull request by msamsel**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Add method to retrieve the content stats. Closes ckeditor/ckeditor5#2568.

BREAKING CHANGE: `_calculateWordsAndCharacters()` no longer fire an `update` event. The function is split. `_updateCountersAndFireUpdate()` from now on will fire a `update` event. 

---

### Additional information

- PR is targeted to `master` which currently is behind `stable`. Changes from `stable` are important to not break docs. (changes on stable modifies namespace of Word count plugin).
- I introduce a breaking change to have the possibility to immediately updated words and characters values without firing an additional `update` event.
- It might be considered to implement the request mentioned in ckeditor/ckeditor5#2577.

### CODE REVIEW

**Review by mlewand — CHANGES_REQUESTED** [review]
I don't like the new proposal because it adds yet another (redundant) way to keep track of the state. Just to enumerate them:

* using [`values()` getter](https://github.com/ckeditor/ckeditor5-word-count/blob/2e27b88b4843d1dc2a5764a4c50f098b923f3d61/src/wordcount.js#L238-L244) (proposed in this PR),
* using [`words`](https://ckeditor.com/docs/ckeditor5/latest/api/module_wordcount_wordcount-WordCount.html#member-words) and [`characters`](https://ckeditor.com/docs/ckeditor5/latest/api/module_wordcount_wordcount-WordCount.html#member-characters) observable properties (already present),
* using the [`update`](https://ckeditor.com/docs/ckeditor5/latest/api/module_wordcount_wordcount-WordCount.html#event-update) event (already present).

That currently makes three ways which I find too many. Instead I'd consider adding a complementary `get:{propertyName}` to the [`Observable` mixin](https://ckeditor.com/docs/ckeditor5/latest/api/module_utils_observablemixin-Observable.html) where the returned (and stored value) might be adjusted. This event should be fired if the client is explicitly accessing the property.

Word count should then listen to these `get:` events, refresh the values and trigger the update event if necessary.

**Comment by mlewand** [comment]
@oleq I'll ask you to take over this PR after me.

**Comment by oleq** [comment]
I agree that bloatin the API is not the right way. I researched a bit and I came up with a solution that reuses the plugin properties to obtain the precise numbers on demand. Check out the code in the [t/6b branch](https://github.com/ckeditor/ckeditor5-word-count/compare/t/6b?expand=1).

You can test it by:
1. Setting throttle to 5000ms,
2. Writing some text
3. Executing `[ editor.plugins.get( 'WordCount' ).words, editor.plugins.get( 'WordCount' ).characters ]` quickly in the console,
4. Observing the values.

cc @mlewand

**Comment by mlewand** [comment]
> Check out the code in the [t/6b branch](https://github.com/ckeditor/ckeditor5-word-count/compare/t/6b?expand=1).

I find it a little hacky, because we're using observables but at the same time we're override standard property access to that, but it does the job and for sure will be quicker than rolling out an entire new API. So all in all looks fine for me 👌

**Comment by oleq** [comment]
Observables work like they used to. You can set them (and they fire events) and you can read them. The up–to–date value retrieval is under the hood.

**Comment by msamsel** [comment]
I've used `t/6b` branch as a source for t/6 branch. So it's forced-pushed now. There was nothing that could be implemented here.
I add unit tests to check if values are updated immediately when someone wants to obtain them.

**Pull request merged**
